In [1]:
import torch
import pandas as pd

In [2]:
pd.set_option("max_colwidth", 300)

## Read Annotated Dataset

In [3]:
#df = pd.read_csv(r'../text-extraction/[labeled]dataset-01.csv', encoding='latin-1')
# df = pd.read_csv(r'../text-extraction/[labeling]dataset-02_500.csv', dtype={
#     'slang': 'string',
#     'text': 'string',
#     'label': 'string'}, encoding='utf-8')
# df = pd.read_excel(r'../Sample_Final12012024_sergiovr01.xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
# df = pd.read_excel(r'../Sample_Final12012024_v2.xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
# df_no_neutrals = pd.read_excel(r'../annotation/Sample_Final12012024_sergiovr01[excluding-neutrals].xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
dfa = pd.read_excel(r'../annotation/6-dataset_2900_comentarios_vr4.xlsx', dtype={
    'slangs': 'string',
    'text': 'string',
    'label': 'string'
})
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3089 entries, 0 to 3088
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   nro                      3089 non-null   int64
 1   id                       3089 non-null   int64
 2   object_id                3089 non-null   int64
 3   ID2                      3089 non-null   object
 4   text                     3089 non-null   string
 5   slangs                   3089 non-null   string
 6   label                    3089 non-null   string
 7   slangs_char_count        3089 non-null   int64
 8   conjunto                 3089 non-null   object
 9   En Muestra_FINAL_Manual  3089 non-null   int64
 10  ANNOTATOR                3080 non-null   float64
dtypes: float64(1), int64(5), object(2), string(3)
memory usage: 265.6+ KB

In [4]:
dfa[['id','text', 'slangs', 'label']].sample(20)

,id,text,slangs,label
3050,140531,Y esta srta ingresó al congreso?? Que nivel!! Y amenazando desde ahora al periodista nivel Maduro 🤦‍♀️🤦‍♀️🤦‍♀️imaginen si entran al poder el sr Castillo ya no habrá libertad de expresión!! 🙆‍♀️🙆‍♀️🙆‍♀️,"maduro,",3
665,105324,Angelow Pachas después de mi dolor con tu sodexo 🙊🙊🙊,"pacha,",2
1744,12703,todos los días chifa jajajaj Brenda Dessiré mira yo tal cual 🤣 atún con fideos. Ya me sie to gaston,"chifa,",2
1481,11467,Hola Cholo me encantan sus vídeos 😁😅,"cholo,",1
485,24121,Brandyn Varas Espinola Rj Nc Esos Juanes de la tia se extraña 💔,"vara,",3
2269,28751,El sombrero de la flaca gaaa 😂,"flaca,",1
220,3333,Fernanda Joceline DG Vamos a conseguirlos para el mono 🤭,"mono,",3
1712,13503,Parece el.hueco negro de un pompis🍑 xdddd,"negro,",3
1303,87934,Jajajajaajjaja la china tiene un tacto para detectar cobardes 🤣🤣🤣🤣,"china,",3
2904,35985,Como no pasa un huayco Justo en ese momento 😂😂😂,"huayco,",3
1197,78,Jose Campos Silva preparo el talco 😹,"talco,",3
2729,25628,Se los dije!!!! Es un lobo disfrazado de oveja 🐑 yo NO LE CREÍ nada todo lo que sale de su boca son puras mentiras,"lobo,",3
97,244518,Estan esperando que este vago funcional de palacio los llame para que cuiden la vagancia hecha institucion.🤣🤣🤣,"vago,",3
1628,692,Nicole Feijoo 🤣 ya pa que cagala nomas,"nomas,",3
2141,61561,Cenia Elena Pacta Paricahua Erika Beatriz FC el rencoroso. 🤫🤫🤫🤫🤫,"elena,",0
380,4366,Alexandra nosotras somos full pantallazos y audios,"full,",2
785,41974,Jajaja lo pido es su hígado o corazón de pique 😂😂,"pique,",1
818,25438,A cueva le pasó como a todo futbolista q llega con los grones.. La maldición de la kk!!! 🤣🤣🤣,"grone,",3
2920,58491,La revientas gordo choclo eres una jerva😂😂,"choclo,",3
2353,1645,Koala yo jajaja noo nada que ver jajajaj !!! Y siempre lo hago jajaja sorry amor 😂😂😂😂😂,"sorry,",1

In [5]:
len(dfa)

3089

In [6]:
# df = df[df.ANNOTATOR.isin(["0"])]
dfa = dfa[dfa.label.isin(["1","2","3"])]
#new_df = new_df.loc[:, ['id_slang','slang', 'sentence', 'label']]
dfa = dfa.loc[:, ['text', 'label']]
dfa = dfa.reset_index(drop=True)
dfa = dfa.astype({'label':'int'})
dfa

,text,label
0,BRAVO bravo 👍 dale duro,1
1,Hoy es un día muy duro de trabajo pero gratificante. 🥰🤗🫶👍👏🇵🇪,1
2,Así hubieran publicado sus músicas cuando estaba vivo 😒,3
3,",Mabel Milla 🤣🤣 Tanto Tu en los Tonos 🤣 JAJAJA 😎",1
4,"Pueden ver los monumentos, galerias de Arte, casas históricas y los huequitos de música... esos lugarcitos bizarros donde el tono termina a las 8 de la mañana. Averiguen😘🤣",2
...,...,...
2749,Estas salado igual que yo en tus sorteos🤣😅,3
2750,De seguro ya le paso la resaca,2
2751,Estara con la resaca,2
2752,"Buena frase , sin salado no hay dulce 🤟🏻",1
2753,Estar en la cima de la cordillera blanca es espectacular 😁,1

In [7]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2754 entries, 0 to 2753
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2754 non-null   string
 1   label   2754 non-null   int64
dtypes: int64(1), string(1)
memory usage: 43.2 KB

In [8]:
# label encode
def label_encode(x):
    if x == 1:#positive
        return 2
    if x == 2:#neutral
        return 1
    if x == 3:#negative
        return 0
# label to name
def label2name(x):
    if x == 0:
        return "negative"
    if x == 1:
        return "neutral"
    if x == 2:
        return "positive"

In [9]:
dfa["label"] = dfa["label"].apply(lambda x: label_encode(x))

In [10]:
dfa.sample(n = 15)

,text,label
640,Jajajaja.. Que picón..me reí a no más poder 😂😂,2
204,"Acuña eres una más de los fujirratas , eso se llama traición a la patria , a ti no te enteresa la necesidad del pueblos , te enteresa corrupción y los monopolios 🐀 🐀 🐀 🐀 🐀",0
133,Lo agarro de pavo literalmente 🤣🤣🤣🤣🤣🤣,0
911,Ah pero cuando probaste la bombilla de cuero no decías lo mismo 🤣😂🤣😂😂,1
2596,Rene Mj Zully Mim Pin Georgete Morales Lemuel Jhordany Alvarado Pérez y de yapa QF Gino Yoshitomi Cristóbal.. Nunca vas 🤣,2
1567,Mariella Paz Spiers vamonos pero hasta el salar de Uyuni 🤗🤗,2
649,"Pero quien es Beto ortiz? Un periodista de renombre, de talla?, es un tipo con una moral excelente?. Es un camaleón, es un apestoso, que solo promueve morbosidad, chisme, intriga, promueve el derrame cerebral en los peruanos, con sus programas regalando dinero 💰 a cuesta de que cuenten sus vid...",0
8,Itala Vera Acosta para cuando tu tono así???😂😂😂🤣,1
1159,"Que rico plato. PERÚ, tierra vendecida. Gastronomía de exportación y de lujo. 😎 vista mi tierra JAUJA. Excelentes platos. Desde Beirut un saludo. 😎",2
512,Los q comentan otras vidas...NO tienen nada q hacer digo yo. Como yo en este momento estoy haciendo el vago 😝😸😂,0
279,Saludos desde Miami mi paco y Dale U Todalavida ✌🏻 😎,2
128,Mainor Pavon quiero ir 🥰,2
1875,Hablen de la Sudamérica par de cabros. 🤣😂,0
2373,Entre mineros se extractean 😆,0
311,María pía vente a Casma la ciudad del eterno sol 🌞 está horrible el frío el la capital.,1

In [11]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2754 entries, 0 to 2753
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2754 non-null   string
 1   label   2754 non-null   int64
dtypes: int64(1), string(1)
memory usage: 43.2 KB

In [12]:
dfa.groupby('label').count()

       text
label
0       936
1       810
2      1008

In [13]:
dfa.to_csv('../data/raw_dataset-06.csv', index=False)

In [14]:
len(dfa)

2754

## Load Raw Dataset

In [15]:
# merging two csv files 
dataset_path = '../data/'
df = pd.concat( 
    map(pd.read_csv, [dataset_path + 'raw_dataset-01.csv',
                      dataset_path + 'raw_dataset-02.csv',
                      dataset_path + 'raw_dataset-03.csv',
                      dataset_path + 'raw_dataset-04.csv',
                      dataset_path + 'raw_dataset-05.csv',
                      dataset_path + 'raw_dataset-06.csv']), ignore_index=True)
# print(df) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14589 entries, 0 to 14588
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    14589 non-null  object
 1   label   14589 non-null  int64
dtypes: int64(1), object(1)
memory usage: 228.1+ KB

In [16]:
df["label_name"] = df["label"].apply(lambda x: label2name(x))

In [17]:
df.sample(15)

,text,label,label_name
5118,Tarapoto es de bien paja estuve este mes hay 👍,2,positive
5539,Eres un locazo me encanta como haces tus notas sigue asi muchos existos y si la chica se molestó por las puras 😂😂😂😂,2,positive
7031,No digo la María Pia está en todas jaaaaaaaa🤣🤣🤣🤣🤣🤣🤣🤣🤭🤭🤭🤭🤭🤭🤭Ni una se le escapa 😅😅😅😅😅ahora sigan criticando para q haga otra serie de Novela más famosa se hace jaaaaaaaaaa🤭🤭🤭🤭🤭👈👈👈,0,negative
190,"Qué barbaridad, carajo",0,negative
1842,Estos entraron al poder con una mentalidad según ellos con muchas diferencias a otros ...jaja..pero una vez dentro se amoldaron al toque y asta amante rubia tiene ese Feito 🤢🤣🤣🤣🤣..quienes le creyeron en estos sinvergüenza 🤣🤣...,0,negative
3342,Toda la vida esa Melissa de regalona 🧐🧐,0,negative
5644,"Mucho pecheo.. van a salir perdiendo ambas. Rosangela es congresista de FP , trabajadora fantasma del congreso , hizo pintas senderistas de madrugada para desprestigiar a los manifestantes en las marchas 🤷🏽‍♀️ Ser de VES o de Miraflores no te hace bueno ni malo .",0,negative
1318,Siguen aquí? Podemos hacer una ruta de huacas muy paja y gratis ✌️,2,positive
3330,Ya no se le cree nada a está víbora MI ABUELITA ES VIRGEN..... INCONCIENTE CHARLATANA MENTIROSA TU MARIDO TE DEJARA POR TRAMPOSA..😡😡😡🤬🤬🤢🤢🤮🤮🤮,0,negative
8558,Brenda Alarcon anda practicando 🤣,1,neutral
538,Tenía la peluca rubia de Pelusa en sus manos,1,neutral
4310,"Que muñeca! , me tenes lokito❤💑",2,positive
1423,Qué tipo de privilegios tendrá y cuánto ganará este señor aunado al poder monopólico que día a día destruye la economía del Perú 🤨,0,negative
4826,Los cachos lo volvieron más fuerte 🤣,0,negative
11333,Lamentablemente ese día no le dieron duro y parejo. Y esa son las consecuencias. 😅😅😅,1,neutral

# Split Train, Test and Validaiton

In [18]:

from sklearn.model_selection import train_test_split


random_state=1
train_df_, val_df = train_test_split(df, 
                                    test_size=0.20, 
                                    random_state=random_state, 
                            stratify=df.label.values)

In [19]:

train_df, test_df = train_test_split(train_df_, 
                                    test_size=0.20, 
                                    random_state=42, 
                            stratify=train_df_.label.values)

In [20]:
!ls -l ../data/test.csv ../data/train.csv ../data/val.csv

-rw-rw-r-- 1 darkstar darkstar  335788 Aug 14 22:35 ../data/test.csv
-rw-rw-r-- 1 darkstar darkstar 1425926 Aug 14 22:35 ../data/train.csv
-rw-rw-r-- 1 darkstar darkstar  443623 Aug 14 22:35 ../data/val.csv

In [21]:
len(train_df)

9336

In [22]:
len(val_df)

2918

In [23]:
len(test_df)

2335

In [24]:
train_df.to_csv('../data/train.csv', index=False)
val_df.to_csv('../data/val.csv', index=False)
test_df.to_csv('../data/test.csv', index=False)

In [25]:
!ls -l ../data/test.csv ../data/train.csv ../data/val.csv

-rw-rw-r-- 1 darkstar darkstar  358963 Aug 17 19:53 ../data/test.csv
-rw-rw-r-- 1 darkstar darkstar 1403927 Aug 17 19:53 ../data/train.csv
-rw-rw-r-- 1 darkstar darkstar  441594 Aug 17 19:53 ../data/val.csv

# Push to Hugging Face

In [26]:
from datasets import load_dataset
data_files = {"train": "../data/train.csv", "validation": "../data/val.csv", "test": "../data/test.csv"}
ds = load_dataset("csv", data_files=data_files)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [27]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 9336
    })
    validation: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 2918
    })
    test: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 2335
    })
})

In [28]:
#push to hugging face
#https://huggingface.co/settings/tokens
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [30]:
# ds.push_to_hub("pyupeu/social-media-peruvian-sentiment")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/10 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

README.md:   0%|          | 0.00/745 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/pyupeu/social-media-peruvian-sentiment/commit/c440ef6cdbeab799ed528637d3fd520d68646e18', commit_message='Upload dataset', commit_description='', oid='c440ef6cdbeab799ed528637d3fd520d68646e18', pr_url=None, pr_revision=None, pr_num=None)