In [104]:
import torch
import pandas as pd

In [103]:
pd.set_option("max_colwidth", 300)

## Read Annotated Dataset

In [111]:
#df = pd.read_csv(r'../text-extraction/[labeled]dataset-01.csv', encoding='latin-1')
# df = pd.read_csv(r'../text-extraction/[labeling]dataset-02_500.csv', dtype={
#     'slang': 'string',
#     'text': 'string',
#     'label': 'string'}, encoding='utf-8')
# df = pd.read_excel(r'../Sample_Final12012024_sergiovr01.xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
# df = pd.read_excel(r'../Sample_Final12012024_v2.xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
# df_no_neutrals = pd.read_excel(r'../annotation/Sample_Final12012024_sergiovr01[excluding-neutrals].xlsx', dtype={
#     'slangs': 'string',
#     'text': 'string',
#     'label': 'string'
# })
dfa = pd.read_excel(r'../annotation/6-dataset_2900_comentarios_vr2.xlsx', dtype={
    'slangs': 'string',
    'text': 'string',
    'label': 'string'
})
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   nro                      2900 non-null   int64
 1   id                       2900 non-null   int64
 2   object_id                2900 non-null   int64
 3   ID2                      2900 non-null   object
 4   text                     2900 non-null   string
 5   slangs                   2900 non-null   string
 6   label                    2900 non-null   string
 7   slangs_char_count        2900 non-null   int64
 8   conjunto                 2900 non-null   object
 9   En Muestra_FINAL_Manual  2900 non-null   int64
 10  ANNOTATOR                2900 non-null   int64
dtypes: int64(6), object(2), string(3)
memory usage: 249.3+ KB

In [122]:
dfa[['id','text', 'slangs', 'label']].sample(20)

,id,text,slangs,label
2042,53440,Hablen de la Sudamérica par de cabros. 🤣😂,"cabro,",3
1090,22805,Jajaja Cacho muy bien con los modales..todas son unas chuscas desorganizadas 👋👋👋 Bravo Cacho ...,"cacho,",1
2786,1126,"Yo uso el morado, para cabello liso 👌","liso,",1
1106,54777,Que roche así es! Ahora usan mandiles rosados 🤣,"roche,",3
2783,13459,Juan Carlos Olivares Lucano 😥,"luca,",3
1818,76775,"Cynthia, ojo al piojo 👀","piojo,",2
2770,1308,Que rico como una sopa seca chincha😋😋😋,"sopa,",1
2513,3908,Regia pía no cambies chula 🥰,"chula,",1
2041,41531,Me encanta!!! Mi pedacito de cielo. Jauja que dulzura☀️🍂🍃😘,"jauja,",1
2112,4019,Tania Brito Morales muy tarde llego tu recomendación xk ya término verdad 😂😂 Maria Pia Copello,"brito,",3
926,229689,"Nadie sabe entender, nadie estuvo preparado y en un pais q muchos no tienen las necesidades básicas este documental, pueda darle alguna reflexión a tantas gente 😔😔.","tanta,",3
2182,4018,"Alta facha sin la barba, vamoo Luciano 💪💪","facha,",1
1718,23357,Mariella Paz Spiers vamonos pero hasta el salar de Uyuni 🤗🤗,"salar,",1
2463,13552,"Mi Huancayo ♥️ con sus espectaculares caldos, caldo de cabeza de cordero parte lengua ummm riquísimo 😋","caldo,",1
1449,19312,Aqui en California tambien domos misios🤣🤣,"misio,",1
1336,35036,Nero Ramirez ve por tus chelas 🤣🤣🤣,"chela,",3
1895,73905,Ronald Santa María Encarnación chamo saco el motokarro🤣🤣🤣🤣🤣,"chamo,",1
2325,19948,"⚠️⚠️ ESAS COMPARACIONES NO VAN, KATY PERRY ESTÁ EN UN NIVEL SUPERIOR DE HUMILDAD Y EMPATÍA CON SUS FANS, del otro ni hablar","habla,",3
1232,1003,Arón Levano JAJJAJJAJJAJJAJ ES TU VERSIÓN FEMININAA LA AMIGA DE LA RUBIA JAJAJA 😂😂😂,"rubia,",2
184,23221,Nelly Peñarrieta este es el lugar que te decia por wapp 🙌,"peña,",2

In [126]:
len(dfa)

2900

In [127]:
# df = df[df.ANNOTATOR.isin(["0"])]
dfa = dfa[dfa.label.isin(["1","2","3"])]
#new_df = new_df.loc[:, ['id_slang','slang', 'sentence', 'label']]
dfa = dfa.loc[:, ['text', 'label']]
dfa = dfa.reset_index(drop=True)
dfa = dfa.astype({'label':'int'})
dfa

,text,label
0,BRAVO bravo 👍 dale duro,1
1,Hoy es un día muy duro de trabajo pero gratificante. 🥰🤗🫶👍👏🇵🇪,1
2,Así hubieran publicado sus músicas cuando estaba vivo 😒,3
3,",Mabel Milla 🤣🤣 Tanto Tu en los Tonos 🤣 JAJAJA 😎",1
4,"Pueden ver los monumentos, galerias de Arte, casas históricas y los huequitos de música... esos lugarcitos bizarros donde el tono termina a las 8 de la mañana. Averiguen😘🤣",1
...,...,...
2801,Su sueño frustrado del cucaracho 🤣😅🤣,3
2802,"crea o no, en Dios pero ese día llegará estar delante de Dios vivo y tendrá q rendir cuentas de todo 😔",2
2803,"EL VIDEO QUE BETO ORTIZ, alías ""La cucaracha gorda"" NO QUIERE QUE VEAS 👇😎👇😎👇😎 https://m.facebook.com/story.php?story_fbid=1546057318919366&id=100005453379216",3
2804,Por fin veo una cuca diferente alas de petardas... 🤣😂😈 Y gratis,3
2805,Cuando no la cucaracha gorda haciéndole propaganda a su amada 🤩,3

In [128]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2806 non-null   string
 1   label   2806 non-null   int64
dtypes: int64(1), string(1)
memory usage: 44.0 KB

In [124]:
# label encode
def label_encode(x):
    if x == 1:#positive
        return 2
    if x == 2:#neutral
        return 1
    if x == 3:#negative
        return 0
# label to name
def label2name(x):
    if x == 0:
        return "negative"
    if x == 1:
        return "neutral"
    if x == 2:
        return "positive"

In [129]:
dfa["label"] = dfa["label"].apply(lambda x: label_encode(x))

In [133]:
dfa.sample(n = 15)

,text,label
45,Lo maximo aprendo contigo colorao....quiero tener ese estomago tuyo y no engordar jamas jajaja 😂,2
106,"Esto es la CORRUPCION y todo lo que hizo sin tener todo el poder, imaginense cuando lo tenga, no hay que ser ingenuos, la confiep esta con ansias de cobrar toda su inversión en keiko, recuerden que no hará nada por el país. 🐭🐭🐭🐭. Tuvo mayoría el congreso .blindó a los cuellos blancos ,chat de la...",0
332,Por favor ya no engendren estas cosas....háganse una paja🙏,0
682,El demonio de sotana y la muerte de negro 😁🤣,0
308,A la paco bazan quisiera q' le presenten a marlon torres. Sauuuu 🤣🤣🤣🤣🤣😃,2
1118,El puntaje será mejor en la 2 da gala 💪🏼,2
1906,Hernán Augusto Silva Luna debemos ir allí amor Órganos Punta veleros 😍,2
1069,Se te ve muy regia con ese vestido y con todo lo k te pongas x k tú eres muy bonita 😍 muchas gracias para ti reina,2
362,Esas ratas son peor que Fujimori 😤,0
2423,Yaninna Conhy recuerdas?? Para cagarse de risa🤣🤣🤣🤣,2
1151,Asu esa flaca que espanta clientes 🤦🏽‍♂️,0
1862,Lucia Chamochumbi tu buscando figuritas 😂😂,2
2683,Jijiji...mascaly esta qué 🔥... 🤭... Probando un poco más de su propia sopa,0
2340,Esta vieja esta x su 🐀,0
130,"La mia tiene 1 año 10 meses y a veces hace pataletas...sobretodo en mi casa, cuando estamos en casa de otros o en la calle no 🤔",0

In [134]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2806 non-null   string
 1   label   2806 non-null   int64
dtypes: int64(1), string(1)
memory usage: 44.0 KB

In [135]:
dfa.groupby('label').count()

       text
label
0       978
1       223
2      1605

In [50]:
# dfa.to_csv('../data/raw_dataset-06.csv', index=False)

In [136]:
len(dfa)

2806

## Load Raw Dataset

In [137]:
# merging two csv files 
dataset_path = '../data/'
df = pd.concat( 
    map(pd.read_csv, [dataset_path + 'raw_dataset-01.csv',
                      dataset_path + 'raw_dataset-02.csv',
                      dataset_path + 'raw_dataset-03.csv',
                      dataset_path + 'raw_dataset-04.csv',
                      dataset_path + 'raw_dataset-05.csv',
                      dataset_path + 'raw_dataset-06.csv']), ignore_index=True)
# print(df) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14641 entries, 0 to 14640
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    14641 non-null  object
 1   label   14641 non-null  int64
dtypes: int64(1), object(1)
memory usage: 228.9+ KB

In [140]:
df["label_name"] = df["label"].apply(lambda x: label2name(x))

In [146]:
df.sample(15)

,text,label,label_name
12668,Estuvo bacán lo mejor Gian Marco🎊,2,positive
1877,Ese es el sabor 😁 belleza la dueña de los huevos es due del toro jjjjjj eso les falta a las gringas 🤣🤣🤣🤣🤣,0,negative
8579,"Felicidades, Beto, a seguir dándole duro a la waripoleras. 💪🏼",2,positive
9624,Jape te amooo mi chaparrita ❤️ ❤️ ❤️,2,positive
7157,Jjajaa estuvo buena la escena🤣🤣🤣 La China desia después de la mojada dónde Estoi q ago .lo saco la chucha o m detengo🤣🤣🤣,1,neutral
2547,Le dan tanta pantalla a ese piraña cambien de tema ya aburre 🤪,0,negative
13850,Chino gey lee ps mi comentario déjate de vainas........🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣,0,negative
7321,estoy piña 🙁 ... pero lo bueno es que se pudo apoyar a los chicos que lo necesitan,0,negative
11553,Y es por eso que más de un youtuber lo dice .. como muchos que cómparten entretenimiento en redes y es que es muy pero muy delicado .. te tropiesas con un error ! Bammm todo mundo te odia .. eres lo peor .. al fin y al cabo hay que entender que se equivocó y todo ser humano se equivoca .. me pár...,1,neutral
7985,"Si fuese una tesis de marketing estaria bueno leerlo ""Como volverse millonario en la industria musical sin tener talento para cantar"" osea, no me digas que no es interesante de leer 🤷",0,negative
14309,Y los tombos grabando😒,0,negative
4415,"Betofilo, Estas picón ? 🤔",0,negative
1163,yo fijandone en la pobre oreja no puede más con ese arete🤭🤣😂,0,negative
903,Soy merengue desde que era chiquitito,1,neutral
3289,Buena #Tobi con la bajada 🔥🔥🔥,2,positive

# Split Train, Test and Validaiton

In [147]:

from sklearn.model_selection import train_test_split


random_state=1
train_df_, val_df = train_test_split(df, 
                                    test_size=0.20, 
                                    random_state=random_state, 
                            stratify=df.label.values)

In [148]:

train_df, test_df = train_test_split(train_df_, 
                                    test_size=0.20, 
                                    random_state=42, 
                            stratify=train_df_.label.values)

In [149]:
!ls -l ../data/test.csv ../data/train.csv ../data/val.csv

-rw-rw-r-- 1 darkstar darkstar  338149 Aug 12 23:44 ../data/test.csv
-rw-rw-r-- 1 darkstar darkstar 1340545 Aug 12 23:44 ../data/train.csv
-rw-rw-r-- 1 darkstar darkstar  414755 Aug 12 23:44 ../data/val.csv

In [150]:
len(train_df)

9369

In [151]:
len(val_df)

2929

In [152]:
len(test_df)

2343

In [153]:
train_df.to_csv('../data/train.csv', index=False)
val_df.to_csv('../data/val.csv', index=False)
test_df.to_csv('../data/test.csv', index=False)

In [154]:
!ls -l ../data/test.csv ../data/train.csv ../data/val.csv

-rw-rw-r-- 1 darkstar darkstar  358831 Aug 13 00:03 ../data/test.csv
-rw-rw-r-- 1 darkstar darkstar 1423215 Aug 13 00:03 ../data/train.csv
-rw-rw-r-- 1 darkstar darkstar  440607 Aug 13 00:03 ../data/val.csv

# Push to Hugging Face

In [155]:
from datasets import load_dataset
data_files = {"train": "../data/train.csv", "validation": "../data/val.csv", "test": "../data/test.csv"}
ds = load_dataset("csv", data_files=data_files)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [156]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 9369
    })
    validation: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 2929
    })
    test: Dataset({
        features: ['text', 'label', 'label_name'],
        num_rows: 2343
    })
})

In [100]:
#push to hugging face
#https://huggingface.co/settings/tokens
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [157]:
# ds.push_to_hub("pyupeu/social-media-peruvian-sentiment")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/10 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

README.md:   0%|          | 0.00/706 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/pyupeu/social-media-peruvian-sentiment/commit/d676398d0dc99eed023aec9957451b46eecd96f8', commit_message='Upload dataset', commit_description='', oid='d676398d0dc99eed023aec9957451b46eecd96f8', pr_url=None, pr_revision=None, pr_num=None)